### ISSUE TITLE
Software Requirements Specification Document

### ISSUE THREAD

**Issue by gundermanc** [CatalystOfNostalgia/feckless-weasel#1]
Complete the software spec document for Monday along with inspection report.

For everyone:
@et8109 @hschmack @CatalystOfNostalgia @jamesflinn @raoanjana

**Comment by hschmack** [comment]
https://docs.google.com/document/d/1ib5-PgeWlcuL7H9AtbqOmIURt56Y_yLbsCFUqlyTLeU/edit

Adding a link to the doc just for ease of access.
