### ISSUE TITLE
Create file ranking algorithm

### ISSUE THREAD

**Issue by jamesflinn** [CatalystOfNostalgia/feckless-weasel#114]
From SRS: 

Create an algorithm for assigning a number representing the relevancy of the content. This should use the user’s trust score, the content’s specific upvote/downvote amounts, and the recency of when the content was posted.

**Comment by CatalystOfNostalgia** [comment]
Blocked on #27. The ranking algorithm uses this.

**Comment by CatalystOfNostalgia** [comment]
Implemented. It's a simple algorithm that takes in the files upvote/downvote and the date it was created as inputs.
