### ISSUE TITLE
Finish course page

### ISSUE THREAD

**Issue by jamesflinn** [CatalystOfNostalgia/feckless-weasel#116]

**Comment by hschmack** [comment]
Current changes include:
- Add Course Name to the Course table
- Modify Course.java and CourseTable.java to reflect that addition
- Modify the CourseServlet to take in a course name and error check it
- Department page lists each course as: DeptAcronym + CourseNum: Course Name
- Also added hyperlink back to University from the department page.
- List all files that belong to a page/

Currently waiting on pull #129 which modifies the course/index.jsp page so i can rework in my changes and ensure that everything looks kosher.

**Comment by hschmack** [comment]
Also hoping to include menu at the top of the course page to filter for certain tags

![image](https://cloud.githubusercontent.com/assets/4140291/11359704/7baa6c66-924c-11e5-8ecf-1d38879b7f53.png)
