### ISSUE TITLE
What goes on the front page

### ISSUE THREAD

**Issue by hschmack** [CatalystOfNostalgia/feckless-weasel#127]
We should cement down what we want displayed on our front page
### Ideas:
- List of All Universities
- A quick link to a note taking and/or file uploading page
- A form that a user can input the University / Dept / Course they want to see

We have a lot of potential information to choose from, we could even just display a users preferred university (the one they specify in their acct creation) and display that on the front page if they're logged in.

I think this is relatively important since it'll be our sites first impression and it'll look pretty lame if it's nothing special.

Thoughts @et8109 @CatalystOfNostalgia @gundermanc @raoanjana @jamesflinn ?

**Comment by CatalystOfNostalgia** [comment]
We've added a list of all Universities, a News Feed, and a Create University Button.
