### ISSUE TITLE
Final Presentation 

### ISSUE THREAD

**Issue by raoanjana** [CatalystOfNostalgia/feckless-weasel#134]
URL to presentation: https://docs.google.com/a/case.edu/presentation/d/1HmBlvFIkHyFN6lxtpbn-kJavS3O3ESQJKu_XXF4gv9Q/edit?usp=sharing

**Comment by CatalystOfNostalgia** [comment]
Added the stack slide. We should add a future works slide.

**Comment by hschmack** [comment]
removing "Discussion Boards for Questions" since we don't have those
