### ISSUE TITLE
Investigate testing 

### ISSUE THREAD

**Issue by CatalystOfNostalgia** [CatalystOfNostalgia/feckless-weasel#18]
1) Find how to calculate test coverage 

**Killing the below item and moving to it's own work item #29 because it's a BIGGIE.
2) Add testing to improve coverage on some backend items.

**Comment by gundermanc** [comment]
Hey all, as of now we have full support for JUnit for unit testing, Mockito for mocking frameworks, continuous integration builds with Travis CI, and automated code coverage measurements via Jacoco and Coveralls.

To see code coverage, simply look at: https://github.com/catalystOfNostalgia/feckless-weasel/ and you will see two badges, a build status and a code coverage badge.

To see more detailed code coverage you can either go click the badge and go to the Coveralls web page or you can view the test reports by running gradle jacocoTestReport and looking at the generate HTML in service/build/reports/jacoco.

The generated testing report should be adequate documentation on our testing practices.
