### ISSUE TITLE
Basic page header. Allow search and link to account creation. 

### ISSUE THREAD

**Issue by gundermanc** [CatalystOfNostalgia/feckless-weasel#2]
Includes searching by university, class, and professor.

**Comment by CatalystOfNostalgia** [comment]
Changed the issue to be a header instead of the front page. I don't think we're clear on what exactly we want on the front page for now...

**Comment by CatalystOfNostalgia** [comment]
Also will add a base css class for us to sharez.

**Comment by gundermanc** [comment]
Sounds good to me.

**Comment by CatalystOfNostalgia** [comment]
Finished.
