### ISSUE TITLE
Convert all documents to .pdf

### ISSUE THREAD

**Issue by CatalystOfNostalgia** [CatalystOfNostalgia/feckless-weasel#22]
Let's convert all documents to pdf. Except for user uploaded notes.

**Comment by jamesflinn** [comment]
Only word docs and text files to pdf

**Comment by CatalystOfNostalgia** [comment]
We're closing as won't fix. This is not really doable. No one exposes an API to do this (because such an API would likely be counter intuitive to their business model).
