### ISSUE TITLE
API is Broken: Unable to Complete Action

### ISSUE THREAD

**Issue by hschmack** [CatalystOfNostalgia/feckless-weasel#51]
REST endpoints give "Unable to Complete Action javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder;"

Initial Stackoverflowing suggests that this may be a dependency issue

We only have 2 occurrences of UriBuilder in the code (Users1Resource and UserSessions1Resource) and commenting those classes out and rebuilding does not fix the issue

**Comment by hschmack** [comment]
This
 http://stackoverflow.com/questions/29134098/java-lang-abstractmethoderror-javax-ws-rs-core-uribuilder-uriljava-lang-string

suggests that we have a conflict since 'javax:javaee-api:7.0' uses JAX-RS 2 
whereas Jersey 1 (we're using 1.13) uses JAX-RS 1

This causes a weird namespace conflict. However when the JAVA EE api dependency is removed we have a whole lot of build errors since we get ServiceException from that jar. @gundermanc any thoughts? You're more familiar with how we build than i am

**Comment by gundermanc** [comment]
This is a known issue. I'll take a look.

**Comment by hschmack** [comment]
@gundermanc if we're removing the REST endpoints then this issue isn't a problem. Feel free to close it if you agree

**Comment by gundermanc** [comment]
I agree, we should remove the REST end points. They lower our overall code coverage % yet are pointless to unit test and they are providing no advantage over using Servlets. Also, they require JSON Request and Response classes (even more code) to do anything.

I added issue #52 to remove REST end points and JSON code.
