### ISSUE TITLE
Upload files to directory other than project directory

### ISSUE THREAD

**Issue by jamesflinn** [CatalystOfNostalgia/feckless-weasel#61]

**Comment by gundermanc** [comment]
Idk if this helps, but they upload to the project directory because we are starting the service from the shell in the project directory and it's a relative path. We could instead hardcode to the current user's directory since tomcat on a production server would normally run as a different user.

**Comment by CatalystOfNostalgia** [comment]
@jamesflinn indicated that this isn't really a bug. I'm going to close it. There aren't any repercussions to just using the project directory.
