### ISSUE TITLE
Make things pretty

### ISSUE THREAD

**Issue by CatalystOfNostalgia** [CatalystOfNostalgia/feckless-weasel#66]
Uh..twitter bootstrap. Sure.

**Comment by CatalystOfNostalgia** [comment]
Create a styleguide.

**Comment by gundermanc** [comment]
@CatalystOfNostalgia, I think a style guide alone won't accomplish this issue. Styleguide=documentation. Documentation is not typically read/maintained.

Could we abstract this into a few CSS and JSP includes and have you have responsibility for reviewing front-end code and commenting when JSP and CSS does not fit your styleguide?
